version: "3.7"
services:
  cassandra:
    image: docker.io/bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - cassandra_db:/var/lib/cassandra
    
    healthcheck:
      test: [ "CMD", "/opt/bitnami/cassandra/bin/cqlsh", "-u cassandra", "-p cassandra" ,"-e \"describe keyspaces\"" ]
      interval: 15s
      timeout: 10s
      retries: 10

    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra


#  pyspark:
#    build: .

  jupyter_pyspark:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888


volumes:
  cassandra_db:
    driver: local
  